###################################################################
# Audio Feature Option Configuration
###################################################################
G_DUMMY = no
G_ALGO = yes

CFG_MTK_AUDIO_FRAMEWORK_SUPPORT = yes
CFG_TASK_VA_SUPPORT = yes
CFG_TASK_RECORD_SUPPORT = no
CFG_AUDIO_LOG_DEBUG = yes
CFG_AUDIO_DEMO = no
CFG_AUDIO_IPC_UT = no
CFG_AUDIO_DSP_STATE = yes
CFG_HW_RES_MGR = yes
CFG_HOST_READY_NOTIFY_SUPPORT = yes
CFG_VA_PROCESS_CLI_SUPPORT = yes
CFG_DSP_CLK_CLI_SUPPORT = yes
#VAD Adaptor
CFG_AUDIO_VA_VAD_DUMMY = $(G_DUMMY)
CFG_VA_MTK_VAD_SUPPORT = $(G_ALGO)
#Pre-Process Adaptor
CFG_AUDIO_VA_AEC_DUMMY = $(G_DUMMY)
CFG_AUDIO_VA_PREPROC_MTKFFP = $(G_ALGO)
#WW Adaptor
CFG_AUDIO_VA_WW_DUMMY = $(G_DUMMY)
CFG_VA_MTK_WW_LITE_SUPPORT = no
CFG_AMZ_WW_LITE_SUPPORT = $(G_ALGO)
CFG_AMZ_WW_LITE_U_SUPPORT = no
CFG_CADENCE_VFPU_V320 = $(G_ALGO)
CFG_DSPOTTER_SUPPORT = $(G_ALGO)
CFG_DSPOTTER_BASE_VERSION = 0 #0: hey siri  1:zhinengguanjia  2:Hello Aircon
#Utility
CFG_AUDIO_DEBUG_DUMP = no
DYNAMIC_LOAD_MODEL = no
CFG_VA_SW_PRE_GAIN = no
VA_TEST_DEBUG = no
CFG_AUDIO_MTKFFP_LOCAL_TEST = no
CFG_WRAP_DSP_CLI_SUPPORT = no
###################################################################
# Voice Assistant Configuration
###################################################################
#config va task reserve sram size
CFG_VA_TASK_RESERVE_SRAM = 0x10000

#VA Process Control
#config which process is default on
CFG_VA_VAD_DEFAULT_ON = no
CFG_VA_WW_DEFAULT_ON = yes
CFG_VA_PREPROC_DEFAULT_ON = yes

#VAD, WW always on and in one config
CFG_VA_VAD_ALWAYS_ON = 0
CFG_VA_WW_ALWAYS_ON = 1
CFG_VA_VAD_WW_IN_ONE = 0

#VA in buffer length, mili-second
CFG_VA_VAD_BUF_LEN = 500
CFG_VA_VAD_BUF_TYPE = ADSP_MEM_TASK_RESERVE
CFG_VA_VAD_BITWIDTH = 16
CFG_VA_VAD_CHNUM = 1

#VA Preprocessing OUT buffer
CFG_VA_PREPROC_BUF_TYPE = ADSP_MEM_NORMAL_CACHE
#if use AEC, AEC's config
CFG_VA_AEC_OUT_CH_NUM = 2
CFG_AUDIO_ECHO_REF_CH = 2
CFG_VA_AEC_BITWIDTH = 32

#VA in buffer length, mili-second
#if CFG_VA_VAD_WW_IN_ONE, WW_BUF_LEN&TYPE will not be used
CFG_VA_WW_BUF_LEN = 3000
CFG_VA_WW_BUF_TYPE = ADSP_MEM_NORMAL_CACHE
#VA wakeword pre-roll size, mili-second
CFG_VA_WW_PRE_ROLL_LEN = 500
CFG_VA_WW_BITWIDTH = 16
CFG_VA_WW_CHNUM = 1

CFG_VA_PROCESS_SPEED_UP_EN = 1

#VA VOICE UPLOAD BUFFER CONFIG
CFG_VA_VOICE_UPLOAD_CH_NUM = 2
CFG_VA_VOICE_UPLOAD_BITWIDTH = 16
CFG_VA_UPLOAD_SPEED_UP_EN = 1
CFG_VA_UPLOAD_BUF_LEN = 1200

# VA State Control
CFG_VA_WW_TIMEOUT_EN = 1
CFG_VA_WW_TIMEOUT_LEN = 3000
CFG_VA_WW_TOUT_CONTINUE = 30

CFG_VA_IDLE_DSP_CLK = DSP_CLK_13M
CFG_VA_VAD_DSP_CLK  = DSP_CLK_26M
CFG_VA_WW_DSP_CLK   = DSP_CLK_600M
CFG_VA_VOICE_UPLOAD_DSP_CLK = DSP_CLK_600M

CFG_VA_IDLE_SYS_HW = DSP_PSRAM_NONEED
CFG_VA_VAD_SYS_HW  = DSP_PSRAM_NONEED
CFG_VA_WW_SYS_HW   = DSP_PSRAM_NEED
CFG_VA_VOICE_UPLOAD_SYS_HW = DSP_PSRAM_NEED

# DSP State Control
CFG_DSP_SWITCH_STATE_EN = no
CFG_DSP_SWITCH_TIMEOUT_LEN = 1000
CFG_DSP_SWITCH_DSP_CLK = DSP_CLK_26M
CFG_DSP_SWITCH_SYS_HW = DSP_SYS_HW_26M

# Default/Max PLL Value
CFG_DSP_PLL_VALUE = 600000000

CFG_ALIGNMENT_BYTES = 64

CFG_AUDIO_PLAYBACK_SUPPORT = no
CFG_CM4_PLAYBACK_ENABLE = no
CFG_AUDIO_HARDWARE_ENABLE = no
CFG_PROMPT_SOUND_ENABLE = no
CFG_AUDIO_LE_AUDIO_SUPPORT = no
