#UT RTOS
UT_RTOS_ENABLE                      = n

#UT POSIX (When UT_RTOS_ENABLE = y)
UT_POSIX_ENABLE                     = n

#UT Platform
UT_PLATFORM_ENABLE                  = n

#
# Platform Module Feature
#
UT_PLATFORM_LAYOUT_ENABLE           = n
UT_PLATFORM_NVDM_ENABLE             = n
UT_PLATFORM_COREDUMP_ENABLE         = n
UT_PLATFORM_HEAP_ENABLE             = n

#UT HAL
UT_HAL_ENABLE                       = y

#
#HAL Module Features (When UT_HAL_ENABLE = y)
#
UT_HAL_ADC_MODULE_ENABLE            = n
UT_HAL_AES_MODULE_ENABLE            = n
UT_HAL_CACHE_MODULE_ENABLE          = n
UT_HAL_CLOCK_MODULE_ENABLE          = n
UT_HAL_DES_MODULE_ENABLE            = n
UT_HAL_EFUSE_MODULE_ENABLE          = n
UT_HAL_EINT_MODULE_ENABLE           = n
UT_HAL_FLASH_MODULE_ENABLE          = n
UT_HAL_GDMA_MODULE_ENABLE           = n
UT_HAL_GPIO_MODULE_ENABLE           = n
UT_HAL_GPT_MODULE_ENABLE            = n
UT_HAL_I2C_MASTER_MODULE_ENABLE     = n
UT_HAL_NVIC_MODULE_ENABLE           = n
UT_HAL_IRRX_MODULE_ENABLE           = n
UT_HAL_KEYPAD_MODULE_ENABLE         = n
UT_HAL_MD5_MODULE_ENABLE            = n
UT_HAL_MPU_MODULE_ENABLE            = n
UT_HAL_ASIC_MPU_MODULE_ENABLE       = n
UT_HAL_PMU_MODULE_ENABLE            = n
UT_HAL_PSRAM_MODULE_ENABLE          = n
UT_HAL_PWM_MODULE_ENABLE            = n
UT_HAL_RTC_MODULE_ENABLE            = n
UT_HAL_SPI_MASTER_MODULE_ENABLE     = n
UT_HAL_SPI_SLAVE_MODULE_ENABLE      = n
UT_HAL_SD_MODULE_ENABLE             = n
UT_HAL_SDIO_MODULE_ENABLE           = n
UT_HAL_SDIO_SLAVE_MODULE_ENABLE     = n
UT_HAL_SHA_MODULE_ENABLE            = n
UT_HAL_SLEEP_MANAGER_MODULE_ENABLE  = n
UT_HAL_TRNG_MODULE_ENABLE           = n
UT_HAL_UART_MODULE_ENABLE           = n
UT_HAL_SSUSB_GADGET_ENABLE          = n
UT_HAL_SSUSB_HOST_ENABLE            = n
UT_HAL_WDT_MODULE_ENABLE            = n
UT_HAL_DWT_MODULE_ENABLE            = n


#UT_HAL_I2S_MODULE_ENABLE           = n
#UT_HAL_SD_MODULE_ENABLE            = n
#UT_HAL_DCXO_MODULE_ENABLE          = n
