/* Copyright Statement:
 *
 * (C) 2017  Airoha Technology Corp. All rights reserved.
 *
 * This software/firmware and related documentation ("Airoha Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to Airoha Technology Corp. ("Airoha") and/or its licensors.
 * Without the prior written permission of Airoha and/or its licensors,
 * any reproduction, modification, use or disclosure of Airoha Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 * You may only use, reproduce, modify, or distribute (as applicable) Airoha Software
 * if you have agreed to and been bound by the applicable license agreement with
 * Airoha ("License Agreement") and been granted explicit permission to do so within
 * the License Agreement ("Permitted User").  If you are not a Permitted User,
 * please cease any access or use of Airoha Software immediately.
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT AIROHA SOFTWARE RECEIVED FROM AIROHA AND/OR ITS REPRESENTATIVES
 * ARE PROVIDED TO RECEIVER ON AN "AS-IS" BASIS ONLY. AIROHA EXPRESSLY DISCLAIMS ANY AND ALL
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES AIROHA PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH AIROHA SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN AIROHA SOFTWARE. AIROHA SHALL ALSO NOT BE RESPONSIBLE FOR ANY AIROHA
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND AIROHA'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO AIROHA SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT AIROHA'S OPTION, TO REVISE OR REPLACE AIROHA SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * AIROHA FOR SUCH AIROHA SOFTWARE AT ISSUE.
 */

#ifndef __BT_MESH_TIMER_DEFINITION_H__
#define __BT_MESH_TIMER_DEFINITION_H__


#define BT_MESH_TIMER_BEARER_GROUP         0x80000000
#define BT_MESH_TIMER_NETWORK_GROUP        0x81000000
#define BT_MESH_TIMER_TRANSPORT_GROUP      0x82000000
#define BT_MESH_TIMER_ACCESS_GROUP         0x83000000
#define BT_MESH_TIMER_BEACON_GROUP         0x84000000
#define BT_MESH_TIMER_PROVISIONING_GROUP   0x85000000
#define BT_MESH_TIMER_HEALTH_GROUP         0x86000000
#define BT_MESH_TIMER_PROXY_GROUP          0x87000000
#define BT_MESH_TIMER_CONFIG_MODEL_GROUP   0x88000000
#define BT_MESH_TIMER_OTA_GROUP            0x89000000
#define BT_MESH_TIMER_HEARTBEAT_GROUP      0x8a000000
/*!
     @name Bearer Layer timer id
     @brief start from 0xFF000000
     @{
 */
#define BT_MESH_TIMERID_ADV_SEND_CHECK_ID      BT_MESH_TIMER_BEARER_GROUP + 0x00
#define BT_MESH_TIMERID_ADV_SCAN_SWITH BT_MESH_TIMER_BEARER_GROUP + 0x01
#define BT_MESH_TIMERID_ADV_RANDOM_DELAY BT_MESH_TIMER_BEARER_GROUP + 0x02
/*!  @} */


/*!
     @name Network Layer timer id
     @brief start from 0xFF000010
     @{
 */
#define BT_MESH_TIMERID_NETWORK_RELAY_ID  BT_MESH_TIMER_NETWORK_GROUP + 0x00
#define BT_MESH_TIMERID_NETWORK_RELAY_RETRANSMIT_ID  BT_MESH_TIMER_NETWORK_GROUP + 0x01
/*!  @} */

/*!
     @name Transport Layer timer id
     @brief start from 0xFF000020
     @{
 */
#define BT_MESH_TIMERID_TRANSPORT_ACK     BT_MESH_TIMER_TRANSPORT_GROUP + 0x00
#define BT_MESH_TIMERID_TRANSPORT_INCOMP  BT_MESH_TIMER_TRANSPORT_GROUP + 0x01
#define BT_MESH_TIMERID_TRANSPORT_TRANSMISSION  BT_MESH_TIMER_TRANSPORT_GROUP + 0x02
/*!  @} */

/*!
     @name LPN timer id
     @brief start from 0xFF000030
     @{
 */
#define BT_MESH_TIMERID_LPN_FRIEND_REQUEST        BT_MESH_TIMER_ACCESS_GROUP + 0x00
#define BT_MESH_TIMERID_LPN_FRIEND_OFFER        BT_MESH_TIMER_ACCESS_GROUP + 0x01
#define BT_MESH_TIMERID_LPN_RECEIVE   BT_MESH_TIMER_ACCESS_GROUP + 0x02
#define BT_MESH_TIMERID_LPN_NEXT_POLL         BT_MESH_TIMER_ACCESS_GROUP + 0x03
#define BT_MESH_TIMERID_LPN_POLL_TIMEOUT   BT_MESH_TIMER_ACCESS_GROUP + 0x04
#define BT_MESH_TIMERID_LPN_RECEIVE_CONFIRM  BT_MESH_TIMER_ACCESS_GROUP + 0x05
#define BT_MESH_TIMERID_LPN_LOW_POWER_MODE    BT_MESH_TIMER_ACCESS_GROUP + 0x06

/*!  @} */

/*!
     @name Heartbeat timer id
     @brief start from 0xFF000040
     @{
 */
#define BT_MESH_TIMERID_HEARTBEAT_PUBLISH_ID   BT_MESH_TIMER_HEARTBEAT_GROUP + 0x00
#define BT_MESH_TIMERID_HEARTBEAT_SUBSCRIBE_ID BT_MESH_TIMER_HEARTBEAT_GROUP + 0x01
#define BT_MESH_TIMERID_HEARTBEAT_DELAY_ID     BT_MESH_TIMER_HEARTBEAT_GROUP + 0x02
/*!  @} */

/*!
     @name Beacon timer id
     @brief start from 0xFF000050
     @{
 */
#define BT_MESH_TIMERID_BEACON_IVUPDATE        BT_MESH_TIMER_BEACON_GROUP + 0x00
#define BT_MESH_TIMERID_BEACON_PROXY           BT_MESH_TIMER_BEACON_GROUP + 0x01
#define BT_MESH_TIMERID_BEACON_SECURE          BT_MESH_TIMER_BEACON_GROUP + 0x02
#define BT_MESH_TIMERID_BEACON_IVRECOVERY      BT_MESH_TIMER_BEACON_GROUP + 0x03

/*!  @} */

/*!
     @name Provisioning timer id
     @brief start from 0xFF000060
     @{
 */
#define BT_MESH_TIMERID_PROV_TRANSACTION  BT_MESH_TIMER_PROVISIONING_GROUP + 0x00
#define BT_MESH_TIMERID_PROV_PROVISION BT_MESH_TIMER_PROVISIONING_GROUP + 0x01
#define BT_MESH_TIMERID_PROV_PDU_TRANSMISSION BT_MESH_TIMER_PROVISIONING_GROUP + 0x02
#define BT_MESH_TIMERID_PROV_SCAN_UD BT_MESH_TIMER_PROVISIONING_GROUP + 0x03
#define BT_MESH_TIMERID_PROV_TRANSACTION_RETRY  BT_MESH_TIMER_PROVISIONING_GROUP + 0x04
#define BT_MESH_TIMERID_PROV_PB_GATT_ADV BT_MESH_TIMER_PROVISIONING_GROUP + 0x05
#define BT_MESH_TIMERID_PROV_BEACON_ADV BT_MESH_TIMER_PROVISIONING_GROUP + 0x06

/*!  @} */

/*!
     @name Health model timer id
     @brief start from 0xFF000070
     @{
 */
#define BT_MESH_TIMERID_HEALTH_STATUS_ID BT_MESH_TIMER_HEALTH_GROUP + 0x00
/*!  @} */

/*!
     @name Proxy timer id
     @brief start from 0xFF000080
     @{
 */
#define BT_MESH_TIMERID_PROXY_TIMER_ID BT_MESH_TIMER_PROXY_GROUP + 0x00
#define BT_MESH_TIMERID_PROXY_SERVER_TIMER_ID BT_MESH_TIMER_PROXY_GROUP + 0x01
#define BT_MESH_TIMERID_PROXY_NODE_IDENTITY_TIMER_ID BT_MESH_TIMER_PROXY_GROUP + 0x02
#define BT_MESH_TIMERID_PROXY_DELAY_TIMER_ID BT_MESH_TIMER_PROXY_GROUP + 0x03
/*!  @} */

/*!
     @name Configuration model timer id
     @brief start from 0xFF000070
     @{
 */
#define BT_MESH_TIMERID_CONFIG_RESET_ID BT_MESH_TIMER_CONFIG_MODEL_GROUP + 0x00
#define BT_MESH_TIMERID_CONFIG_MODEL_PUBLICATION_ID BT_MESH_TIMER_CONFIG_MODEL_GROUP + 0x01
/*!  @} */


/*! @name OTA timer id
    @{
*/
#define BT_MESH_TIMER_ID_OTA_DISTRIBUTOR_CONTROL        BT_MESH_TIMER_OTA_GROUP + 0x00
#define BT_MESH_TIMER_ID_OTA_DISTRIBUTOR_CHUNK_TRANSFER   BT_MESH_TIMER_OTA_GROUP + 0x01
#define BT_MESH_TIMER_ID_OTA_UPDATER_APPLY BT_MESH_TIMER_OTA_GROUP + 0x02
/*! @}*/

/*! @name System timer id
    @{
 */
#define BT_MESH_TIMER_ID_RX_MESSAGE 0xFF0000B0	
/*! @}*/

#endif // __BT_MESH_TIMER_DEFINITION_H__
