/* Copyright Statement:
 *
 * (C) 2017  Airoha Technology Corp. All rights reserved.
 *
 * This software/firmware and related documentation ("Airoha Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to Airoha Technology Corp. ("Airoha") and/or its licensors.
 * Without the prior written permission of Airoha and/or its licensors,
 * any reproduction, modification, use or disclosure of Airoha Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 * You may only use, reproduce, modify, or distribute (as applicable) Airoha Software
 * if you have agreed to and been bound by the applicable license agreement with
 * Airoha ("License Agreement") and been granted explicit permission to do so within
 * the License Agreement ("Permitted User").  If you are not a Permitted User,
 * please cease any access or use of Airoha Software immediately.
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT AIROHA SOFTWARE RECEIVED FROM AIROHA AND/OR ITS REPRESENTATIVES
 * ARE PROVIDED TO RECEIVER ON AN "AS-IS" BASIS ONLY. AIROHA EXPRESSLY DISCLAIMS ANY AND ALL
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES AIROHA PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH AIROHA SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN AIROHA SOFTWARE. AIROHA SHALL ALSO NOT BE RESPONSIBLE FOR ANY AIROHA
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND AIROHA'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO AIROHA SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT AIROHA'S OPTION, TO REVISE OR REPLACE AIROHA SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * AIROHA FOR SUCH AIROHA SOFTWARE AT ISSUE.
 */
#ifndef _NVKEY_DSPFW_H_
#define _NVKEY_DSPFW_H_

#include "nvkey_id_list.h"

/*NVDM ID string*/
//out
#define NVKEY_DSP_PARA_DIGITAL_GAINTABLE_A2DP_STRING   "E010"
#define NVKEY_DSP_PARA_DIGITAL_GAINTABLE_LINEIN_STRING "E011"
#define NVKEY_DSP_PARA_DIGITAL_GAINTABLE_SCO_STRING    "E012"
#define NVKEY_DSP_PARA_DIGITAL_GAINTABLE_VP_STRING     "E014"
#define NVKEY_DSP_PARA_DIGITAL_GAINTABLE_RT_STRING     "E015"
#define NVKEY_DSP_PARA_DIGITAL_GAINTABLE_SCO_NB_STRING "E017"

#define NVKEY_DSP_PARA_ANALOG_GAINTABLE_A2DP_STRING    "E020"
#define NVKEY_DSP_PARA_ANALOG_GAINTABLE_LINEIN_STRING  "E021"
#define NVKEY_DSP_PARA_ANALOG_GAINTABLE_SCO_STRING     "E022"
#define NVKEY_DSP_PARA_ANALOG_GAINTABLE_VP_STRING      "E024"
#define NVKEY_DSP_PARA_ANALOG_GAINTABLE_RT_STRING      "E025"
#define NVKEY_DSP_PARA_ANALOG_GAINTABLE_SCO_NB_STRING  "E027"

//in
#define NVKEY_DSP_PARA_DIN_GP_TABLE_LINEIN_STRING      "E031" //Need check
#define NVKEY_DSP_PARA_AIN_GP_TABLE_LINEIN_STRING      "E041" //Need check

#define NVKEY_DSP_PARA_DIN_GP_TABLE_SCO_STRING         "E050"
#define NVKEY_DSP_PARA_DIN_GP_TABLE_SCO_NB_STRING      "E051"
#define NVKEY_DSP_PARA_DIN_GP_TABLE_AT_STRING          "E052"
#define NVKEY_DSP_PARA_AIN_GP_TABLE_SCO_L_STRING       "E060"
#define NVKEY_DSP_PARA_AIN_GP_TABLE_SCO_R_STRING       "E061"
#define NVKEY_DSP_PARA_AIN_GP_TABLE_SCO_NB_L_STRING    "E062"
#define NVKEY_DSP_PARA_AIN_GP_TABLE_SCO_NB_R_STRING    "E063"
#define NVKEY_DSP_PARA_AIN_GP_TABLE_AT_L_STRING        "E064"
#define NVKEY_DSP_PARA_AIN_GP_TABLE_AT_R_STRING        "E065"


enum DSP_FW_NVKEY_e {
    NVKEY_DSP_PARA_AUDIOSETTING             = NVKEYID_DSP_FW_PARA_AUDIOSETTING,
    NVKEY_DSP_PARA_DATADUMP                 = 0xE001,
    NVKEY_DSP_PARA_AFE                      = 0xE002,
    NVKEY_DSP_PARA_VOLUME_PARAMETERS        = NVKEYID_DSP_FW_PARA_VOLUME_PARAMETERS,
    NVKEY_DSP_PARA_DIGITAL_GAINTABLE_A2DP   = NVKEYID_DSP_FW_PARA_DIGITAL_GAINTABLE_A2DP,
    NVKEY_DSP_PARA_DIGITAL_GAINTABLE_LINE   = NVKEYID_DSP_FW_PARA_DIGITAL_GAINTABLE_LINE,
    NVKEY_DSP_PARA_DIGITAL_GAINTABLE_SCO    = NVKEYID_DSP_FW_PARA_DIGITAL_GAINTABLE_SCO,
    NVKEY_DSP_PARA_DIGITAL_GAINTABLE_VC     = NVKEYID_DSP_FW_PARA_DIGITAL_GAINTABLE_VC,
    NVKEY_DSP_PARA_DIGITAL_GAINTABLE_VP     = NVKEYID_DSP_FW_PARA_DIGITAL_GAINTABLE_VP,
    NVKEY_DSP_PARA_DIGITAL_GAINTABLE_RT     = NVKEYID_DSP_FW_PARA_DIGITAL_GAINTABLE_RT,
    NVKEY_DSP_PARA_DIGITAL_GAINTABLE_AT     = NVKEYID_DSP_FW_PARA_DIGITAL_GAINTABLE_AT,
    NVKEY_DSP_PARA_DIGITAL_GAINTABLE_SCO_NB = NVKEYID_DSP_FW_PARA_DIGITAL_GAINTABLE_SCO_NB,
    NVKEY_DSP_PARA_ANALOG_GAINTABLE_A2DP    = NVKEYID_DSP_FW_PARA_ANALOG_GAINTABLE_A2DP,
    NVKEY_DSP_PARA_ANALOG_GAINTABLE_LINE    = NVKEYID_DSP_FW_PARA_ANALOG_GAINTABLE_LINE,
    NVKEY_DSP_PARA_ANALOG_GAINTABLE_SCO     = NVKEYID_DSP_FW_PARA_ANALOG_GAINTABLE_SCO,
    NVKEY_DSP_PARA_ANALOG_GAINTABLE_VC      = NVKEYID_DSP_FW_PARA_ANALOG_GAINTABLE_VC,
    NVKEY_DSP_PARA_ANALOG_GAINTABLE_VP      = NVKEYID_DSP_FW_PARA_ANALOG_GAINTABLE_VP,
    NVKEY_DSP_PARA_ANALOG_GAINTABLE_RT      = NVKEYID_DSP_FW_PARA_ANALOG_GAINTABLE_RT,
    NVKEY_DSP_PARA_ANALOG_GAINTABLE_AT      = NVKEYID_DSP_FW_PARA_ANALOG_GAINTABLE_AT,
    NVKEY_DSP_PARA_ANALOG_GAINTABLE_SCO_NB  = NVKEYID_DSP_FW_PARA_ANALOG_GAINTABLE_SCO_NB,
    NVKEY_DSP_PARA_DIN_GAINTABLE_A2DP       = NVKEYID_DSP_FW_PARA_DIN_GAINTABLE_A2DP,
    NVKEY_DSP_PARA_DIN_GAINTABLE_LINE       = NVKEYID_DSP_FW_PARA_DIN_GAINTABLE_LINE,
    NVKEY_DSP_PARA_DIN_GAINTABLE_SCO        = NVKEYID_DSP_FW_PARA_DIN_GAINTABLE_SCO,
    NVKEY_DSP_PARA_DIN_GAINTABLE_VC         = NVKEYID_DSP_FW_PARA_DIN_GAINTABLE_VC,
    NVKEY_DSP_PARA_DIN_GAINTABLE_VP         = NVKEYID_DSP_FW_PARA_DIN_GAINTABLE_VP,
    NVKEY_DSP_PARA_DIN_GAINTABLE_RT         = NVKEYID_DSP_FW_PARA_DIN_GAINTABLE_RT,
    NVKEY_DSP_PARA_DIN_GAINTABLE_AT         = NVKEYID_DSP_FW_PARA_DIN_GAINTABLE_AT,
    NVKEY_DSP_PARA_AIN_GAINTABLE_A2DP       = NVKEYID_DSP_FW_PARA_AIN_GAINTABLE_A2DP,
    NVKEY_DSP_PARA_AIN_GAINTABLE_LINE       = NVKEYID_DSP_FW_PARA_AIN_GAINTABLE_LINE,
    NVKEY_DSP_PARA_AIN_GAINTABLE_SCO        = NVKEYID_DSP_FW_PARA_AIN_GAINTABLE_SCO,
    NVKEY_DSP_PARA_AIN_GAINTABLE_VC         = NVKEYID_DSP_FW_PARA_AIN_GAINTABLE_VC,
    NVKEY_DSP_PARA_AIN_GAINTABLE_VP         = NVKEYID_DSP_FW_PARA_AIN_GAINTABLE_VP,
    NVKEY_DSP_PARA_AIN_GAINTABLE_RT         = NVKEYID_DSP_FW_PARA_AIN_GAINTABLE_RT,
    NVKEY_DSP_PARA_AIN_GAINTABLE_AT         = NVKEYID_DSP_FW_PARA_AIN_GAINTABLE_AT,
    NVKEY_DSP_PARA_AIN_GAINTABLE_SCO_NB     = NVKEYID_DSP_FW_PARA_AIN_GAINTABLE_SCO_NB,
    NVKEY_DSP_PARA_DIN_GP_TABLE_SCO         = NVKEYID_DSP_FW_PARA_DIN_GP_TABLE_SCO,
    NVKEY_DSP_PARA_DIN_GP_TABLE_SCO_NB      = NVKEYID_DSP_FW_PARA_DIN_GP_TABLE_SCO_NB,
    NVKEY_DSP_PARA_DIN_GP_TABLE_AT          = NVKEYID_DSP_FW_PARA_DIN_GP_TABLE_AT,
    NVKEY_DSP_PARA_AIN_GP_TABLE_SCO_L       = NVKEYID_DSP_FW_PARA_AIN_GP_TABLE_SCO_L,
    NVKEY_DSP_PARA_AIN_GP_TABLE_SCO_R       = NVKEYID_DSP_FW_PARA_AIN_GP_TABLE_SCO_R,
    NVKEY_DSP_PARA_AIN_GP_TABLE_SCO_NB_L    = NVKEYID_DSP_FW_PARA_AIN_GP_TABLE_SCO_NB_L,
    NVKEY_DSP_PARA_AIN_GP_TABLE_SCO_NB_R    = NVKEYID_DSP_FW_PARA_AIN_GP_TABLE_SCO_NB_R,
    NVKEY_DSP_PARA_AIN_GP_TABLE_AT_L        = NVKEYID_DSP_FW_PARA_AIN_GP_TABLE_AT_L,
    NVKEY_DSP_PARA_AIN_GP_TABLE_AT_R        = NVKEYID_DSP_FW_PARA_AIN_GP_TABLE_AT_R,

    NVKEY_DSP_PARA_LEVEL_PERCENTAGE_SCO     = NVKEYID_APP_VOLUME_SCO_SETTING,
    NVKEY_DSP_PARA_LEVEL_PERCENTAGE_A2DP    = NVKEYID_APP_VOLUME_A2DP_SETTING,
    NVKEY_DSP_PARA_LEVEL_PERCENTAGE_MP3     = NVKEYID_APP_VOLUME_MP3_SETTING,
    NVKEY_DSP_PARA_LEVEL_PERCENTAGE_SCO_MIC = NVKEYID_APP_VOLUME_SCOMIC_SETTING,
    NVKEY_DSP_PARA_LEVEL_PERCENTAGE_VPRT    = NVKEYID_APP_VOLUME_VPRT_SETTING,
    NVKEY_DSP_PARA_LEVEL_PERCENTAGE_LINEIN  = NVKEYID_APP_VOLUME_LINEIN_SETTING,
};

#endif /* _NVKEY_DSPFW_H_ */
