#ifndef __LE_MAIN_H__
#define __LE_MAIN_H__

#include "main.h"

#define LE_SECTION_FUNC NORMAL_SECTION_FUNC
#define LE_SECTION_DATA NORMAL_SECTION_DATA
#define LE_SECTION_RODATA NORMAL_SECTION_RODATA
#define LE_SECTION_BSS NORMAL_SECTION_BSS

#endif
